apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitrix-webhook
  namespace: psi-opora
  labels:
    app: bitrix-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitrix-webhook
  template:
    metadata:
      labels:
        app: bitrix-webhook
    spec:
      containers:
        - name: bitrix-webhook
          image: registry.orixon.ru/psi-opora-bitrix-webhook:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: psi-opora-env
---
apiVersion: v1
kind: Service
metadata:
  name: bitrix-webhook
  namespace: psi-opora
spec:
  type: NodePort
  selector:
    app: bitrix-webhook
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30020
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitrix-webhook-http
  namespace: psi-opora
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`psi-opora-bitrix-webhook.orixon.ru`)
      kind: Rule
      services:
        - name: bitrix-webhook
          port: 3000
      middlewares:
        - name: redirect-to-https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitrix-webhook-https
  namespace: psi-opora
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`psi-opora-bitrix-webhook.orixon.ru`)
      kind: Rule
      services:
        - name: bitrix-webhook
          port: 3000
  tls:
    certResolver: letsencrypt
