CREATE TABLE "book_preorder_orders" (
	"id" text PRIMARY KEY NOT NULL,
	"order_no" serial NOT NULL,
	"messenger" text NOT NULL,
	"user_id" text NOT NULL,
	"chat_id" text,
	"name" text,
	"phone" text,
	"email" text,
	"consent_at" timestamp,
	"deal_id" integer,
	"status" text DEFAULT 'reserved' NOT NULL,
	"payment_choice" text,
	"reserved_at" timestamp DEFAULT now() NOT NULL,
	"paid_at" timestamp,
	"declined_at" timestamp,
	"preorder_price_expires_at" timestamp,
	"drip_step" integer DEFAULT 0 NOT NULL,
	"drip_last_sent_at" timestamp,
	"drip_deferred_at" timestamp,
	"drip_any_click_at" timestamp,
	"shipping_name" text,
	"shipping_address" text,
	"promo_code" text,
	"source" text,
	"campaign" text,
	"ym_client_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
